language: node_js

node_js:
  - "6"

git:
  depth: 2

before_install:
  - openssl aes-256-cbc -K $encrypted_b281b2f14922_key -iv $encrypted_b281b2f14922_iv -in .travis-ci/deploy.key.enc -out .travis-ci/deploy.key -d
  - chmod 400 .travis-ci/deploy.key
  - eval `ssh-agent -s`
  - ssh-add .travis-ci/deploy.key
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

script:
  - git checkout $BRANCH
  - node build/index.js --silent

deploy:
  provider: script
  script: .travis-ci/deploy.sh
  skip_cleanup: true
  on:
    branch: travis-ci-fixes
